name: test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  dummy:
  
    runs-on: [self-hosted, linuxtest]
   # runs-on: ubuntu-latest
    
    steps:
    - name: dummy
      run: echo "Dummy stage just to be more that one in this test..."
  build:
    needs: dummy
    runs-on: ubuntu-latest

    steps:
    
    - name: build
      run: echo "build app"
  deploy:
    needs: build
    runs-on: ubuntu-latest
      
    steps:
    - name: deploy
      run: echo "deploy app"
