name: PHP Composer

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dummy stage just to be more that one in this test..."
      
  build:
    runs-on: ubuntu-latest
    needs: dummy
    steps:
    - uses: actions/checkout@v2
    
    - name: test
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "deploy app"
      
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
